import Head from "next/head";
import Hero from "@/components/landingPage/Hero";
import Header from "@/components/Header";
import Mission from "@/components/landingPage/Mission";
import HowItWorks from "@/components/landingPage/HowItWorks";
import Footer from "@/components/landingPage/Footer";
import Connect from "@/components/landingPage/Connect";

export default function Home() {
    return (
        <>
            <Head>
                <title>Cyber Alley</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Header />
            <Hero />
            <Mission />
            <HowItWorks />
            <Connect />
            <Footer />
        </>
    );
}
