import Head from "next/head";
import Hero from "@/components/landingPage/Hero";
import Header from "@/components/landingPage/Header";

export default function Home() {
    return (
        <>
            <Head>
                <title>Cyber Alley</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Header />
            <Hero />
        </>
    );
}
