import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export default function Home() {
    return (
        <>
            <Head>
                <title>Cyber Alley</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <div
                style={{
                    position: "relative",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    width: "calc(100% - 20px)",
                    height: "calc(100vh - 20px)",
                    margin: "10px",
                    background:
                        "linear-gradient(150deg,rgba(181, 181, 181, 1) 0%, rgba(180, 183, 177, 1) 26%, rgba(153, 230, 67, 1) 100%)",
                    clipPath:
                        "polygon(0 10%, 10% 0%, 30% 0, 30% 10%, 56% 10%, 63% 0%, 75% 0, 75% 10%, 100% 10%, 100% 90%, 90% 100%, 0 100%);",
                }}
            >
                <Image
                    src="/hero.png"
                    alt="hero"
                    width={900}
                    height={900}
                    style={{
                        clipPath:
                            "polygon(calc(0% + 3px) calc(10% + 3px), calc(10% + 3px) calc(0% + 3px), calc(30% - 3px) calc(0% + 3px), calc(30% - 3px) calc(10% + 3px), calc(56% + 3px) calc(10% + 3px), calc(63% + 3px) calc(0% + 3px), calc(75% - 3px) calc(0% + 3px), calc(75% - 3px) calc(10% + 3px), calc(100% - 3px) calc(10% + 3px), calc(100% - 3px) calc(90% - 3px), calc(90% - 3px) calc(100% - 3px), calc(0% + 3px) calc(100% - 3px));",

                        width: "100%",
                        height: "100%",
                        objectFit: "cover",
                        objectPosition: "center",
                    }}
                />

                <h1
                    style={{
                        color: "white",
                        position: "absolute",
                        bottom: 80,
                        left: 20,
                    }}
                >
                    TAKE PART ON SOMETHING BIGGER
                </h1>

                <button
                    style={{
                        color: "black",
                        border: "none",
                        backgroundColor: "#dbff29ff",
                        padding: "5px 10px",
                        fontSize: "2rem",
                        position: "absolute",
                    }}
                >
                    START
                </button>
            </div>
        </>
    );
}
